[package]
name = "libsquish_wrapper"
version = "0.1.0"
authors = ["April Wade <wayedt@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1"
